name: Test Environment Variables

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      VAR1: "Hello"
    steps:
      - name: Define VAR2
        run: echo "VAR2=${VAR1} World" >> $GITHUB_ENV

      - name: Show VAR2
        run: echo "VAR2 is $VAR2"
